### ISSUE TITLE
aws-jdbc-driver 1.1.4 + Hikari4.0.3 + AWSSecretsManagerPluginFactory - JDBC access denied

### ISSUE THREAD

**Issue by peter-jang** [awslabs/aws-mysql-jdbc#361] opened 2023-02-14 07:11 UTC
### Describe the bug

Hi,
I'm trying to use AWS secret manager with HikariCP and aws-mysql-jdbc driver.
I followed document described here and it looks the initial JDBC connection working well.
However every 20minute or so, I get access denied error from my RDS Mysql error logs.
If I omit FailoverConnectionPluginFactory and NodeMonitoringConnectionPluginFactory from my application.property 
these error logs are not appear anymore.

I think that monitoring plugin could not get credential information which provided by AWS SecretManager.

When I start my application I see there's 10 connection made to RDS MySQL from my (ec2) server 
it is because HikariCP create 10 connection to manage connection pool.
While  1 connection out of 10 works well (I can query to RDS from my application),
I get 9 of "[Note] Access denied for user 'ec2-user'@'172.31.39.60' (using password: NO)" error 

### Expected Behavior

There should be no access denied error even though I used AWS secret manager with monitoring plugin.
If I turn off the enhanced monitoring feature (omit FailoverConnectionPluginFactory and NodeMonitoringConnectionPluginFactory from my application.property), I don't see access denied error anymore which is expected behavior.

### Current Behavior

every 20 min after starting application, I get access denied error from RDS error log.
Also, I was able to capture the access denied error via tcpdump as soon as the application was starting.

<img width="1156" alt="Screen Shot 2023-02-14 at 3 48 11 PM" src="https://user-images.githubusercontent.com/11946914/218660480-8e5653f5-4df0-4042-962d-c7da920b3b9e.png">

<img width="1508" alt="Screen Shot 2023-02-14 at 4 17 31 PM" src="https://user-images.githubusercontent.com/11946914/218666160-600ae7cb-b466-43bf-8c74-a3bc475361ea.png">

If I add below static credential information to application.property then error log disappears.
but I can't use this because I want to do credential rotation using AWS Secret Manager
```
spring.datasource.username=admin
spring.datasource.password=password-string
```

### Reproduction Steps

Create simple spring boot application with below configuration (I've used maven)
build project and run application, wait 20min to see RDS error logs.
or you can capture traffic dump using tcpdmp while application starting.
`tcpdump -nn -X port 3306`

**pom.xml**
```
                <dependency>
                         <groupId>software.aws.rds</groupId>
                         <artifactId>aws-mysql-jdbc</artifactId>
                         <version>1.1.4</version>
                </dependency>
                <dependency>
                        <groupId>com.zaxxer</groupId>
                        <artifactId>HikariCP</artifactId>
                        <version>4.0.3</version>
                </dependency>
                <dependency>
                         <groupId>software.amazon.awssdk</groupId>
                         <artifactId>secretsmanager</artifactId>
                         <version>2.20.0</version>
                </dependency>
```

**application.property**
```
spring.datasource.url=jdbc:mysql:aws://testdb.cluster-cev6v6ac6pit.ap-northeast-2.rds.amazonaws.com:3306/exampledb?allowPublicKeyRetrieval=true&useSSL=false&socketTimeout=0&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true

spring.datasource.driverClassName=software.aws.rds.jdbc.mysql.Driver

spring.datasource.hikari.data-source-properties.connectionPluginFactories=software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.AWSSecretsManagerPluginFactory,software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPluginFactory,software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPluginFactory

spring.datasource.hikari.data-source-properties.secretsManagerSecretId=rds!cluster-3987e3c1-228d-4c58-9191-ed0844bbdb5a
spring.datasource.hikari.data-source-properties.secretsManagerRegion=ap-northeast-2
```

### The AWS JDBC Driver for MySQL version used

1.1.4

### JDK version used

openjdk version "1.8.0_352" OpenJDK Runtime Environment (build 1.8.0_352-b08) OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

### Operating System and version

Amazon Linux2 5.10.162-141.675.amzn2.x86_64

**Comment by aaronchung-bitquill** [comment] 2023-02-14 19:44
Hi @peter-jang 

Thanks for reaching out and reporting this issue. We will looking into this and post updates as we investigate.

Thank you for your patience!

**Comment by abedali** [comment] 2023-02-20 16:08
@aaronchung-bitquill Is there an ETA on when this issue would be resolved?

**Comment by aaronchung-bitquill** [comment] 2023-02-21 20:28
Hi @abedali 
Thanks for your interest in this issue and reaching out.
Unfortunately at the moment, we're still looking into this. We'll post an update and ETA once we know more and have a solution in mind. 
Thank you!

**Comment by aaronchung-bitquill** [comment] 2023-02-25 00:05
Hi @peter-jang 
I'm currently trying to reproduce the issue and was wondering if you could provide more details of the following?

- How do you have HikariCP configured? Besides a pool size of 10, what other values do you have set?
- How are you querying the database? Are you using any data access frameworks or libraries like Hibernate or JdbcTemplate? 
- Are you seeing any Access Denied errors on application side logs too, or is it only on the RDS logs?
- What OS and type of EC2 instance are you using? 

Any code snippets or other details you can provide would also be greatly appreciated.

Thank you

**Comment by peter-jang** [comment] 2023-02-25 14:00
Hi,
Thanks for your time to taking a look this issue.

Actually, this issue reported to me by one of my customer and he could not give me any sample code due to security policy that his company has.
So, I had to create my own example springboot application.
I just downloaded empty project from SpringBoot official webpage and added aws jdbc driver and hikariCP to the pom.xml to reproduce the issue.

every configuration beside pool size of 10 is default and I did not even touched it.

I heard that my customer is using Hibernate to access database but I think it doesn't matter
because I could reproduce issue without using data access frameworks.

The "Access Denied" error is only appears on RDS error logs and not on application error and this is also confirmed by my customer too.

So, how do I know one out of 10 database connection was working is that I checked tcpdump while application is starting.
I could see one connection (which I could confirm with source port number) send SELECT query to the RDS which is not possible without successful login.

<img width="211" alt="Screen Shot 2023-02-25 at 10 45 36 PM" src="https://user-images.githubusercontent.com/11946914/221360295-472e30ef-bae7-4503-938b-8866141c20bc.png">

<img width="213" alt="Screen Shot 2023-02-25 at 10 45 42 PM" src="https://user-images.githubusercontent.com/11946914/221360297-612ad094-33ab-464f-a7c3-9eeb88ae2372.png">

<img width="217" alt="Screen Shot 2023-02-25 at 10 45 47 PM" src="https://user-images.githubusercontent.com/11946914/221360302-3e8cbac6-11c9-401a-bdde-67617c5e9eb0.png">

Also, my customer confirmed me that their application working well while they see same "Access error" logs.


I've attached sample spring boot code I've used to reproduce.
You will need to edit application.properties to match your secret manager id, region and RDS endpoint url as well.

```
mvn clean package
java -jar target/SpringBootJdbcHikariConnectionPoolExample-0.0.1-SNAPSHOT.jar
```

After starting sample spring boot application, you will see total 27 lines of access error log in CloudWatch logs
I believe this is due to a total of 3 login retries (9 connections * 3 retries = 27).

[SpringBootJdbcHikariConnectionPoolExample.zip](https://github.com/awslabs/aws-mysql-jdbc/files/10831308/SpringBootJdbcHikariConnectionPoolExample.zip)

**Comment by aaronchung-bitquill** [comment] 2023-03-08 19:10
@peter-jang I wanted to check in to let you know we have not forgotten about this issue and are working on a solution. Also, thank you for sharing all those details. They were very helpful.

**Comment by aaronchung-bitquill** [comment] 2023-03-13 21:13
Hi @peter-jang 
We've just merged in a fix. Could you kindly checkout our [snapshot](https://github.com/awslabs/aws-mysql-jdbc#using-a-snapshot-of-the-driver) build and let us know if the issue still persists? 
Thank you!

**Comment by peter-jang** [comment] 2023-03-15 10:00
Hi,
I am currently running a test application to see if the issue is reproduced.
I confirmed that using the aws-mysql-jdbc-1.1.5-20230313.210220-9.jar version, I do not get an ACCESS DENIED error on application startup as before, so the bug I reported seems to be fixed.

I have set Secret Manager to automatically rotate the credential every 4 hours, and I want to make sure there are no issues with the credential rotation process.
However, I have noticed that I am temporarily getting a number of access denied errors whenever the credential is rotated, 

The difference is that this access denied error was "USING PASSWORD: NO" before the bug fix, and now it's "USING PASSWORD: YES".
So I'm assuming that the access denied error that occurs after the bug fix is caused by trying to access with an old credential that was used in Secret Manager.

is this expected behavior or is there something I'm missing or something I should check?

<img width="1126" alt="Screen Shot 2023-03-15 at 6 58 00 PM" src="https://user-images.githubusercontent.com/11946914/225274717-2d9da286-9194-42f0-9700-e9c88c82b449.png">

**Comment by peter-jang** [comment] 2023-03-15 10:43
Let me test the "Alternating users rotation strategy" in Secret Manager to see if it resolves the temporary access denied error.

**Comment by peter-jang** [comment] 2023-03-16 13:19
I changed the rotation strategy of the secret manager to "Alternating users rotation strategy", but after that I am still getting 5 access denied errors every time I rotate the secret. (2 errors from Lambda function and 3 from application ec2)
However, the application seems to be working fine.
It seems to be connecting to the database normally through retry logic.
I will look forward to the official release of version 1.1.5.
Thank you.

**Comment by aaronchung-bitquill** [comment] 2023-03-17 00:31
Hi @peter-jang 

Thanks for getting back to us on this one. We really appreciate it! 

The access denied with "USING PASSWORD: YES" are expected. The AwsSecretsManagerPlugin logic holds the credentials in cache until a connection attempt fails (like because of password rotation). At this point, the plugin will try to refresh the credentials and try to connect again. 

Thank you!

**Closed** 2023-03-17 17:44 UTC
Labels: bug
