### ISSUE TITLE
Quartz schedulers failing with driver version 1.1.0

### ISSUE THREAD

**Issue by jnagulavancha** [awslabs/aws-mysql-jdbc#283] opened 2022-09-20 22:52 UTC
### Describe the bug

We were trying to switch from MariaDB driver to AWS JDBC driver but the quartz schedulers in our applications are failing with below error I did not observe this issue if I use version 1.0.0

 ERROR [] [scheduler_QuartzSchedulerThread] [ErrorLogger] An error occurred whi
le scanning for the next triggers to fire. tag=
       org.quartz.JobPersistenceException: Couldn't acquire next trigger: Parameter index out of range (1 > number of
parameters, which is 0).
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
       at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
       Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:1
29)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:9
7)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:8
9)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:6
3)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStat
ement.java:1396)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPr
eparedStatement.java:1409)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.setString(ClientPreparedStatem
ent.java:1776)
       at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.lambda$invoke$0(
ConnectionProxy.java:323)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.DefaultConnectionPlugin.execute(DefaultConn
ectionPlugin.java:80)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPlugin.execute(Node
MonitoringConnectionPlugin.java:178)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(F
ailoverConnectionPlugin.java:248)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionP
luginManager.java:138)
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.invoke(Connectio
nProxy.java:320)
       at com.sun.proxy.$Proxy98.setString(Unknown Source)
       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setString(NewProxyPreparedStatement.java:618)
       at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2610)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2844)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
       at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
       at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)

### Expected Behavior

Quartz scheduler to work and make queries to the database. 

### Current Behavior

       Caused by: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
       at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:1
29)

### Reproduction Steps

https://examples.javacodegeeks.com/enterprise-java/quartz/quartz-scheduler-example/

### The AWS JDBC Driver for MySQL version used

1.0.0

### JDK version used

java 11.0.3 2019-04-16 LTS

### Operating System and version

CentOS 7

**Comment by jnagulavancha** [comment] 2022-10-04 20:06
Unfortunately I don't have the query and reverted all my setup.

**Comment by hsuamz** [comment] 2022-10-12 22:56
Thank you @jnagulavancha,

We have tried reproducing this issue on our end, but have been unable to do so. If you encounter this issue again, please re-open or a create a new issue and share the query being executed, provide driver logs, application logs, and the surrounding code where the issue is present.

I will close this ticket for now since we cannot reproduce the issue.

Thanks.

**Closed by hsuamz** 2022-10-12 22:56 UTC
Labels: bug, Information required
