### ISSUE TITLE
Several re-connection issues with Aurora v2

### ISSUE THREAD

**Issue by albanf** [awslabs/aws-mysql-jdbc#303] opened 2022-10-27 21:03 UTC
### Describe the bug

After a failover, some connections are invalid:
* they are connected to the replica instead of the writer
* the failover is disabled

### Expected Behavior

Connections to writer should reconnect to the new writer, and the failover should still be enabled

### Current Behavior

After a failover, some connections are invalid:
* they are connected to the replica instead of the writer
* the failover is disabled

### Reproduction Steps

It happens with multiple connections only, because some go through the failover process, which updates the topology in the shared cache.
Then other connections are using incorrectly the new topology to update actual connection.

### Possible Solution

PR: https://github.com/awslabs/aws-mysql-jdbc/pull/302

### The AWS JDBC Driver for MySQL version used

1.1.1

### JDK version used

11

### Operating System and version

Alpine 3.16

**Comment by karenc-bq** [comment] 2022-11-18 18:58
Ongoing discussion in PR #302

**Comment by amka-ar** [comment] 2023-05-19 21:30
Hello. I want to raise this issue.

First, by explicitly invoking `setReadOnly` each time we get a connection from the pool, we were able to [auto-recover](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1205) from most `The MySQL server is running with the --read-only option so it cannot execute this statement` cases we have had. Looks like this behavior is not documented.

But even with this feature we got one unrecoverable case and we believe the cause was the same as [here](https://github.com/awslabs/aws-mysql-jdbc/pull/400#issuecomment-1530850280) (two records with `MASTER_SESSION_ID` during the failover and `isMultiWriterCluster`). In 1.1.7 `isMultiWriterCluster` was removed, but at the same time, `AuroraTopologyService` started removing the oldest `MASTER_SESSION_ID` record (previous writer) from the list of hosts. And that brings us to this issue.

Part of the `FailoverConnectionPlugin` recover logic (eg, [1](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1292), [2](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L547)) depends on consistency between `hosts` and `currentHostIndex`. But they can get out of sync because during [updateHostIndex](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1291) in [updateTopologyIfNeeded](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L737), [pickNewConnection](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L639) uses the old topology, can get connection to the previous writer and set `currentHostIndex` to 0. And then [this.hosts updated with the new topology](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L738).

The sequence is as follows:
1. Failover starts
2. The first connection failovers, refreshes the topology cache
3. During the topology refresh, DB returns two records with `MASTER_SESSION_ID`, AuroraTopologyService [only stores the recent one](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java#L284), thus removing the previous writer from the list of hosts
4. Another connection hits [updateTopologyIfNeeded](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L735), gets list from the cache
5. [It doesn't find current host](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1295) (previous writer) in the latest topology
6. [pickNewConnection is invoked](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1307), uses the old topology (`this.hosts`) and may succeed because the previous writer may have started as a reader before `connectionTimeout`.
7. `currentHostIndex` is set to `WRITER_CONNECTION_INDEX` (0)
8. `this.hosts` [is updated to the latest topology](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L738), now `currentHostIndex` points to a wrong host in the `this.hosts` list
9. The connection will not recover to the correct writer, because `isWriterHostIndex` will return true, and [currentHost](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1292) in `updateHostIndex` is not actually current host

We did a simulation in debug, `topologyService.processQueryResults` was overwritten and returned:
1. cluster-0 + cluster-1
2. cluster-1 (W)
3. cluster-1 (W) + cluster-0 (R)

Here are values for step 2:
[List<HostInfo> latestTopology = this.topologyService.getTopology(connection, forceUpdate);](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#LL734C5-L736C1)
![image (15)](https://github.com/awslabs/aws-mysql-jdbc/assets/41328117/7d3536ba-d305-408c-a63e-570faf73e0f0)
[updateHostIndex(latestTopology);](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#LL737C5-L737C37)
![image (16)](https://github.com/awslabs/aws-mysql-jdbc/assets/41328117/0d8fc35d-3eec-4020-90fc-459cedc06d7e)
[this.hosts = latestTopology;](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#LL738C5-L738C33)
![image (17)](https://github.com/awslabs/aws-mysql-jdbc/assets/41328117/1db16def-12fe-4fdf-925d-841c54864713)
Affected connections didn't recover.

Additional notes (but these seems recoverable):
* [topologyService.getHostByName](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java#L409) may return null because of cache expiration (not sure if this is intentional or not)
* [isFailoverEnabled](https://github.com/awslabs/aws-mysql-jdbc/blob/main/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L309) will return false in case if we get two `MASTER_SESSION_ID` records from DB

Thank you

**Comment by crystall-bitquill** [comment] 2023-06-27 21:05
Hi @amka-ar,

Apologies for the delayed response.

Thank you for raising this issue. PR #426 has been created to address this problem.

Regarding your additional notes,

1. It is possible for `topologyService.getHostByName` to return null if the connection host is not found in the latest topology, but this is intentional. In the failover plugin, `topologyService.getHostByName` is used to get the host index. If it returns null, the host index resolves to `NO_CONNECTION_INDEX`, which is handled by the plugin.

2. The method `isFailoverEnabled` will not return false in the case of multiple `MASTTER_SESSION_ID` records. The changes made in PR #405 have removed the isMultiWriterCluster flag, and will ensure that the topology will not contain multiple writer instances. Additionally, the `isFailoverEnabled` method was changed in the same PR to not check for multiple writers.

**Comment by crystall-bitquill** [comment] 2023-07-14 16:49
Hi @amka-ar,

We've recently merged a [fix](https://github.com/awslabs/aws-mysql-jdbc/pull/426). Could you kindly checkout the latest [snapshot build](https://github.com/awslabs/aws-mysql-jdbc#using-a-snapshot-of-the-driver) and let us know if the issue persists?

Thank you!

**Comment by crystall-bitquill** [comment] 2023-07-19 21:24
Hi @amka-ar,

I wanted to check in to see if the issue was resolved with the snapshot build.

If there are no more updates on this ticket in the next few days, it will be closed. However, if you have any further questions or comments please feel free to create a new issue or to reopen this one.

Thank you!

**Closed** 2023-07-25 20:37 UTC
Labels: bug
