### ISSUE TITLE
Connection sometimes doesn't failover with clusterInstanceHostPattern parameter

### ISSUE THREAD

**Issue by arosso** [awslabs/aws-mysql-jdbc#377] opened 2023-03-24 00:13 UTC
### Describe the bug

When a manual failover is triggered on our 2 node RDS Aurora cluster, the connection sometimes doesn't failover to the new writer and stays on the reader. This causes any inserts/updates to return an Exception: 

java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement 
 
The situation doesn't resolve itself until the connection is broken and re-established. 

This does not happen every time but probably 1 out of 2 or 3 failovers. 

We use a custom Route53 hostname for our RDS cluster, and therefore add the `clusterInstanceHostPattern` to the JDBC parameters. From what we can tell, when this parameter is present the, the situation happens. If we use the cluster name directly without the `clusterInstanceHostPattern` parameter the failover consistently works. Even using the cluster endpoint but including the `clusterInstanceHostPattern` parameter triggers the issue.

### Expected Behavior

We are expecting that during a failover all our connections migrate to the new writer.

### Current Behavior

During a failover, some connections remain on the old writer which is now a reader and we then get exceptions like:

`java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement`

### Reproduction Steps

Attached is a Main.java that reproduces the issue. It is modeled on the code sample provided in the JDBC readme. It's the simplest example we could provide. It uses the Hikari connection pool. We have tried Hikari 5.0.1, and the AWS driver 1.1.3 and 1.1.4 but the behavior is the same.

To run:

java -cp aws-mysql-jdbc-1.1.4.jar:HikariCP-4.0.3.jar:slf4j-api-1.7.21.jar:slf4j-jdk14-1.7.21.jar:. Main "jdbc:mysql:aws://clusterhostname:3306/db?profileSQL=true&clusterInstanceHostPattern=?.clusterid.us-east-1.rds.amazonaws.com&enableClusterAwareFailover=true&logger=Slf4JLogger" "user" 'pass'

This has all logging on so it's very verbose. The code simply runs some transactions continually until it is stopped. While it's running if you initiate a failover of your RDS cluster sometimes you'll start seeing the read-only exception mentioned above. It seems like the connection is not re-established to the new writer. 

We've excluded DNS caching issues. DNS records are all set to 5s TTL and the Java sample sets caching to a minimum. 
[jdbctest.tar.gz](https://github.com/awslabs/aws-mysql-jdbc/files/11057357/jdbctest.tar.gz)

### Possible Solution

Without `clusterInstanceHostPattern`, using the cluster endpoint, everything works. There seems to be logic in the code that triggers different behavior based on `clusterInstanceHostPattern`. We assume it has to do with detecting if the driver is talking to an Aurora cluster or just a simple MySQL server. Maybe a new parameter could be added to force this behavior if the issue cannot be fixed.

### The AWS JDBC Driver for MySQL version used

1.1.4

### JDK version used

Corretto 11.0.17.8.1

### Operating System and version

Amazon Linux 2 (4.14.296-222.539.amzn2.x86_64)

**Comment by aaronchung-bitquill** [comment] 2023-03-24 01:11
Hi @arosso 

Thank you for reaching and raising this issue. 

We will be investigating this and keep you posted with updates.

Thank you!

**Comment by sergiyvamz** [comment] 2023-03-24 21:46
Hello @arosso 

Thanks for reaching out and raising this issue.

We appreciate that you provided a sample app, however, without driver logs it's quite challenging to troubleshoot the issue. Our further explanations and suggestions are based on the code you provided and your  description.

AWS JDBC MySQL driver requires `clusterInstanceHostPattern` configuration parameter if a custom domain name is used in connection string. This parameter isn't mentioned at the top of `Main.java` so we can assume you omitted this parameter while it's required.

We noticed that custom exception handling for Hikari connection pool is commented in `Main.java`. We'd like to stress your attention on importance of providing such custom handler since it helps Hikari connection pool to properly recognize failover exceptions and to avoid evicting valid/operational connection from the pool.

We assume that a custom domain that you use in connection string is an alias to a cluster writer endpoint. (Could you please confirm it?) Cluster writer endpoint is a convenient to connect to a current cluster writer node. However the resolution of the endpoint changes when a failover event occurs on a cluster. For example, cluster writer endpoint points to a node "A" before failover, and it points to node "B" after cluster failover. In general, if your application has a connection pool that uses cluster writer endpoint, then you should expect that connections opened before cluster failover are resolved/opened to a node "A". Connections that open after cluster failover are connected to node "B". As result, an application connection pool has a mix of connections to nodes "A" and "B". Since roles of node "A" and "B" change, there's a chance that a connection pool returns a connection to a node that is a reader while the application expects to get a connection to a writer. Running any DML statements on a read-only connection leads to an error that you mentioned above. 

While the driver can properly handle a cluster failover and to follow to a new writer node for all connections that are being actively used when failover occurs, it has a little control over idle connections sitting in a connection pool.

We'd also like to gauge interest if you'd be able to try out the `aws-advanced-jdbc-wrapper`. The `aws-advanced-jdbc-wrapper` officially supports Aurora PostgreSQL and it currently is experimental for Aurora MySQL. Since the `aws-advanced-jdbc-wrapper` can be used in conjunction with the Community MySQL JDBC Driver or the Community MariaDB JDBC Driver, compatibility is preserved. The team is currently focusing on validation testing, but the `aws-advanced-jdbc-wrapper` has intended design changes that improve idle connections tracking. We expect to call this feature non-experimental once validation testing is completed and we'd interested in gathering any feedback that you may have.

https://github.com/awslabs/aws-advanced-jdbc-wrapper

**Comment by arosso** [comment] 2023-03-24 22:53
@sergiyvamz - Thank you for your response. 

A couple of clarifications:

* We commented out the Hikari connection pool exception handling as it didn't seem to affect the issue. The behavior experienced is the same with or without the exception handling. 
* The situation happens even with a jdbc url such as this:

`jdbc:mysql:aws://[clustername].cluster-[clusterid].us-east-1.rds.amazonaws.com:3306/db?clusterInstanceHostPattern=?.clusterid.us-east-1.rds.amazonaws.com`

Meaning that even without the custom domain we still see the same issue if we have the `clusterInstanceHostPattern` parameter. But yes, our custom domain is a CNAME to the cluster writer endpoint with a TTL of 5s. 

If we instead use this jdbc url:

`jdbc:mysql:aws://[clustername].cluster-[clusterid].us-east-1.rds.amazonaws.com:3306/db` 

we see no issues during failover. 

* In our test we have 1 connection in the connection pool. If the connection is in use (working on a transaction) the debug is different than if the connection is in the pool and unused but as far as we can tell the failover happens once the connection is checked out of the queue. 

I am sensitive to posting debug logs and list our cluster names but here is a redacted log of what we've seen. When everything works we see this in the debug:

```
[2023-03-16 21:23:34 091] [FINEST ] [ClusterAwareConnectionProxy] isRds=true
[2023-03-16 21:23:34 091] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false
[2023-03-16 21:23:34 091] [FINEST ] [AuroraTopologyService] clusterId='[clusername].cluster-[clusterid].us-east-1.rds.amazonaws.com:3306'
[2023-03-16 21:23:34 092] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[clusterid].us-east-1.rds.amazonaws.com', port=3306, database='geowarehouse'
[2023-03-16 21:23:34 092] [FINEST ] [ClusterAwareConnectionProxy] explicitlyReadOnly=false
[2023-03-16 21:23:34 092] [FINEST ] [ClusterAwareConnectionProxy] explicitlyReadOnly=false
[2023-03-16 21:23:34 124] [INFO   ] [QUERY] SET autocommit=1 [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: -1, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 124] [INFO   ] [FETCH]  [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: -1, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 126] [INFO   ] [QUERY] SET sql_mode='STRICT_TRANS_TABLES' [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 1, connection-id: 82, statement-id: -1, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 126] [INFO   ] [FETCH]  [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 1, connection-id: 82, statement-id: -1, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 127] [INFO   ] [QUERY] set session transaction read write [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: -1, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 127] [INFO   ] [FETCH]  [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: -1, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 127] [FINE   ] [ClusterAwareConnectionProxy] Connected to: [software.aws.rds.jdbc.mysql.shading.com.mysql.cj.conf.HostInfo@6f0ca692](mailto:software.aws.rds.jdbc.mysql.shading.com.mysql.cj.conf.HostInfo@6f0ca692) :: {host: "[writernode].[clusterid].us-east-1.rds.amazonaws.com", port: 3306, hostProperties: {verifyServerCertificate=false, profileSQL=true, logger=Slf4JLogger, enableClusterAwareFailover=true, sslMode=REQUIRED, useSSL=true, TOPOLOGY_SERVICE_SERVER_ID=[writernode], requireSSL=true, dbname=geowarehouse, TOPOLOGY_SERVICE_SESSION_ID=MASTER_SESSION_ID, connectionCollation=utf8mb4_general_ci, connectTimeout=0, socketTimeout=0, TOPOLOGY_SERVICE_LAST_UPDATE_TIMESTAMP=2023-03-16 21:23:33.69312, characterEncoding=UTF-8, TOPOLOGY_SERVICE_REPLICA_LAG_IN_MILLISECONDS=0.0}}
[2023-03-16 21:23:34 127] [FINEST ] [ClusterAwareConnectionProxy] isRds=true
[2023-03-16 21:23:34 127] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false
[2023-03-16 21:23:34 127] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[clusterid].us-east-1.rds.amazonaws.com', port=3306, database='db'
[2023-03-16 21:23:34 127] [FINEST ] [ClusterAwareConnectionProxy] isClusterTopologyAvailable=true
[2023-03-16 21:23:34 128] [INFO   ] [QUERY] SELECT @@aurora_server_id [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: 0, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 128] [INFO   ] [FETCH]  [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: 0, resultset-id: 0,       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-16 21:23:34 129] [FINEST ] [ClusterAwareConnectionProxy] Topology obtained:
   [0]: [writernode].[clusterid].us-east-1.rds.amazonaws.com
   [1]: [readernode].[clusterid].us-east-1.rds.amazonaws.com
[2023-03-16 21:23:34 129] [INFO   ] [QUERY] SELECT @@aurora_server_id [Created on: Thu Mar 16 21:23:34 UTC 2023, duration: 0, connection-id: 82, statement-id: 0, resultset-id: 0,      at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
```

Note the reference to the connection to the writer. When it doesn't work this is the debug:

```
[2023-03-17 21:50:48 134] [FINEST ] [ClusterAwareConnectionProxy] isRds=true
[2023-03-17 21:50:48 134] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false
[2023-03-17 21:50:48 134] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[clusterid].us-east-1.rds.amazonaws.com', port=3306, database='db'
[2023-03-17 21:50:48 156] [INFO   ] [QUERY] SET autocommit=1 [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 1, connection-id: 1040, statement-id: -1, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 156] [INFO   ] [FETCH]  [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 0, connection-id: 1040, statement-id: -1, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 157] [INFO   ] [QUERY] SET sql_mode='STRICT_TRANS_TABLES' [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 0, connection-id: 1040, statement-id: -1, resultset-id: 0,  at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)] 
[2023-03-17 21:50:48 157] [INFO   ] [FETCH]  [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 1, connection-id: 1040, statement-id: -1, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 157] [FINEST ] [ClusterAwareConnectionProxy] isRds=true  
[2023-03-17 21:50:48 157] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false 
[2023-03-17 21:50:48 157] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[clusterid].us-east-1.rds.amazonaws.com', port=3306, database='db'  
[2023-03-17 21:50:48 158] [INFO   ] [QUERY] SELECT SERVER_ID, SESSION_ID, LAST_UPDATE_TIMESTAMP, REPLICA_LAG_IN_MILLISECONDS FROM information_schema.replica_host_status WHERE time_to_sec(timediff(now(), LAST_UPDATE_TIMESTAMP)) <= 300 ORDER BY LAST_UPDATE_TIMESTAMP DESC [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 1, connection-id: 1040, statement-id: 0, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)] 
[2023-03-17 21:50:48 158] [INFO   ] [FETCH]  [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 0, connection-id: 1040, statement-id: 0, resultset-id: 0,     at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 159] [FINEST ] [ClusterAwareConnectionProxy] isClusterTopologyAvailable=true
[2023-03-17 21:50:48 159] [INFO   ] [QUERY] SELECT @@aurora_server_id [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 0, connection-id: 1040, statement-id: 0, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 159] [INFO   ] [FETCH]  [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 0, connection-id: 1040, statement-id: 0, resultset-id: 0,     at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
[2023-03-17 21:50:48 159] [FINEST ] [ClusterAwareConnectionProxy] Topology obtained: 
   [0]: [writernode].[clusterid].us-east-1.rds.amazonaws.com
   [1]: [readernode].[clusterid].us-east-1.rds.amazonaws.com
[2023-03-17 21:50:48 160] [INFO   ] [QUERY] SELECT @@aurora_server_id [Created on: Fri Mar 17 21:50:48 UTC 2023, duration: 1, connection-id: 1040, statement-id: 0, resultset-id: 0,    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)]
```

In this output we don't see the connection statement and some of the statements are slightly different (explicitlyReadOnly=false is missing for instance). 

We'll take a look at the aws advanced jdbc wrapper. Doesn't hurt to try. :)

**Comment by sergiyvamz** [comment] 2023-03-28 00:34
Hi @arosso 

As for the importance of custom exception handling for Hikari connection pool. I can provide an extract from a real log. Sensitive details have been masked and it's for illustration purposes. There're line numbers at the beginning of each line for visibility and reference.


```
1	[2023-03-27 16:57:13 848] [FINEST ] [ClusterAwareConnectionProxy] isRds=true 
2	[2023-03-27 16:57:13 850] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false 
3	[2023-03-27 16:57:13 851] [FINEST ] [AuroraTopologyService] clusterId='[cluster-id].cluster-[masked].us-east-1.rds.amazonaws.com:3306' 
4	[2023-03-27 16:57:13 877] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[masked].[region].rds.amazonaws.com', port=3306, database='[masked]' 
5	[2023-03-27 16:57:13 878] [FINEST ] [ClusterAwareConnectionProxy] explicitlyReadOnly=false 
6	[2023-03-27 16:57:14 842] [FINE   ] HikariPool-1 - Added connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@3f6f6701 
	...
7	[2023-03-27 16:57:14 933] [INFO   ] ------------------> Close Connection 
8	[2023-03-27 16:57:14 947] [FINE   ] HikariPool-1 - Reset (autoCommit) on connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@3f6f6701 
	...
10	[2023-03-27 16:58:25 646] [FINEST ] [ClusterAwareConnectionProxy] Detected an exception while executing a command. 
11	[2023-03-27 16:58:25 652] [FINE   ] [ClusterAwareConnectionProxy] Starting writer failover procedure. 
12	[2023-03-27 16:58:35 735] [FINE   ] [ClusterAwareWriterFailoverHandler] Successfully connected to the new writer instance: '[instance-id].[masked].[region].rds.amazonaws.com:3306' 
13	[2023-03-27 16:58:35 751] [WARNING] HikariPool-1 - Failed to validate connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@68878f6d (The active SQL connection has changed due to a connection failure. Please re-configure session state if required.). Possibly consider using a shorter maxLifetime value. 
14	[2023-03-27 16:58:35 754] [FINE   ] HikariPool-1 - Closing connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@68878f6d: (connection is dead) 
15	[2023-03-27 16:58:35 763] [FINEST ] [ClusterAwareConnectionProxy] isRds=true 
16	[2023-03-27 16:58:35 763] [FINEST ] [ClusterAwareConnectionProxy] isRdsProxy=false 
17	[2023-03-27 16:58:35 764] [FINEST ] [AuroraTopologyService] clusterId='[cluster-id].cluster-[masked].[region].rds.amazonaws.com:3306' 
18	[2023-03-27 16:58:35 764] [FINEST ] [AuroraTopologyService] clusterInstance host='?.[masked].[region].rds.amazonaws.com', port=3306, database='[masked]' 
19	[2023-03-27 16:58:35 764] [FINEST ] [ClusterAwareConnectionProxy] explicitlyReadOnly=false 
20	[2023-03-27 16:58:35 829] [FINE   ] HikariPool-1 - Added connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@367f0576 
	...

```

Opening a new connection starts with lines 1-6. Hikari reports that a new connection is added to the pool (line 6). An application runs and executes SQL statements, and then it closes a connection (line 7). Hikari doesn't close the connection but
returns it to the pool for further use (line 8). 

When cluster failover occurs, an application loses connectivity to a connected node. The current SQL being executed is interrupted and the driver notifies that failover procedure is started (lines 10-11). It takes some time
to wait till the DB cluster completes failover and the driver reconnects to a new writer node (line 12). Since this moment the connection object gets operational again. It raises an exception and notifies that failover procedure is completed. However
Hikari doesn't recognize this exception as a "good" one and evicts the connection from the pool (line 14). 

Depending on connection pool settings, Hikari may need to open a new connection (lines 15-20). While opening a new connection, the driver tries to establish a connection to a cluster writer endpoint. A short time after failover (20-60s),
a cluster endpoint may be obsolete and may resolve to an old writer. There's no guarantee that it resolves to a new writer. Practically it means that there's a big chance that this new connection will be open to an old writer and will be read-only. 

If the application code had custom exception handlers for Hikari connection pool, there would be no eviction of a valid connection from the pool (lines 13-14). Hikari wouldn't need to open a new connection (lines 15-20) and there wouldn't no lottery with cluster endpoint.

If the application code had custom exception handlers for Hikari connection pool, there would be no eviction of a valid connection from the pool (lines 13-14). Hikari wouldn't need to open a new connection (lines 15-20) and there wouldn't no lottery with cluster endpoint.

Connection parameter `clusterInstanceHostPattern` is optional for cluster endpoints. The driver set this parameter to `clusterInstanceHostPattern=?.clusterid.us-east-1.rds.amazonaws.com` by default. It seems that the parameter value that you use in the connection string is the same as the default value so I believe you can omit this parameter.

**Comment by arosso** [comment] 2023-03-28 20:15
@sergiyvamz - Ok, I think I see what you're saying. Hikari thinks the connection is dead, so instead of using the direct node address is now using the cluster address or route53 custom name in the jdbc url and because of DNS flushing delays there is a chance that it could go back to the reader. 

This seems to happen a lot more often for us with the custom name (which is a CNAME to the cluster writer endpoint) even if we have a TTL of 1s. I still don't understand why we have not yet seen it when using the cluster writer endpoint directly without clusterInstanceHostPattern. Maybe the timing of having one less CNAME makes the difference.

I noticed that this seems to happen consistently to connections that are unused in the pool. If the connection is in use, and the Hikari Exception class is in place, the connection is fine. However, the connections in the pool seem to get into this state and when handed out to do work are not writable. 

But if this is the case, what can we do about this? Our only thought at this point is to have a connection test SQL that checks for the innodb_read_only flag and fails if the connection is read only. I don't see any way to tell Hikari to avoid evicting the connection that is in the pool.

**Comment by arosso** [comment] 2023-03-29 23:28
@sergiyvamz - Thanks for investigating. 

I'll note one more thing in looking at this. When looking at the debug for what happens when using the cluster writer endpoint I see this (abbreviated):

```
1.   [2023-03-29 20:41:30 262] [FINE   ] [ClusterAwareWriterFailoverHandler] Successfully connected to the new writer instance: '[newwriter].[clusterid].us-east-1.rds.amazonaws.com:3306'
2.   [2023-03-29 20:41:30 263] [FINE   ] [ClusterAwareConnectionProxy] Connected to: software.aws.rds.jdbc.mysql.shading.com.mysql.cj.conf.HostInfo@2e8a398c :: {host: "[newwriter].[clusterid].us-east-1.rds.amazonaws.com", port: 3306, hostProperties: {verifyServerCertificate=false, profileSQL=true, logger=Slf4JLogger, enableClusterAwareFailover=true, sslMode=REQUIRED, useSSL=true, TOPOLOGY_SERVICE_SERVER_ID=[newwriter], requireSSL=true, dbname=db, TOPOLOGY_SERVICE_SESSION_ID=MASTER_SESSION_ID, connectionCollation=utf8mb4_general_ci, connectTimeout=0, socketTimeout=0, TOPOLOGY_SERVICE_LAST_UPDATE_TIMESTAMP=2023-03-29 20:41:30.258153, characterEncoding=UTF-8, TOPOLOGY_SERVICE_REPLICA_LAG_IN_MILLISECONDS=0.0}}
3.    [2023-03-29 20:41:30 268] [WARNING] HikariPool-1 - Failed to validate connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@7d5bddb6 (The active SQL connection has changed due to a connection failure. Please re-configure session state if required.). Possibly consider using a shorter maxLifetime value.
4.    [2023-03-29 20:41:30 269] [FINE   ] HikariPool-1 - Closing connection software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl@7d5bddb6: (connection is dead)
5.    [2023-03-29 20:41:30 339] [FINE   ] [ClusterAwareConnectionProxy] Connected to: software.aws.rds.jdbc.mysql.shading.com.mysql.cj.conf.HostInfo@2e8a398c :: {host: "[newwriter].[clusterid].us-east-1.rds.amazonaws.com", port: 3306, hostProperties: {verifyServerCertificate=false, profileSQL=true, logger=Slf4JLogger, enableClusterAwareFailover=true, sslMode=REQUIRED, useSSL=true, TOPOLOGY_SERVICE_SERVER_ID=[newwriter], requireSSL=true, db, TOPOLOGY_SERVICE_SESSION_ID=MASTER_SESSION_ID, connectionCollation=utf8mb4_general_ci, connectTimeout=0, socketTimeout=0, TOPOLOGY_SERVICE_LAST_UPDATE_TIMESTAMP=2023-03-29 20:41:30.258153, characterEncoding=UTF-8, TOPOLOGY_SERVICE_REPLICA_LAG_IN_MILLISECONDS=0.0}}
6.   [2023-03-29 20:41:30 354] [INFO   ] ------------------> Get Connection 0
```

Basically the failover kicks in, changes the underlying connection over to the new writer, but then Hikari closes the connection because of the issue we've been discussing. However, once a new connection is created, I see a connection from the ClusterAwareConnectionProxy being made to the new writer. It seems like there is logic that reads the topology and decides to connect to the writer, rather than the reader. 

That would make sense to me... if a new connection is created, and for whatever reason (e.g. DNS caching), it finds itself on a reader, it should be able to get the node metadata and reconnect to the writer instead. 

I don't see a similar pattern like 5 when using the custom domain endpoint. It seems like the logic is slightly different. There still is debug about reading the topology but I never see the Connect statement. Maybe it's using a cached copy of the topology (but not printing it out) or runs through a different code path because it's not recognized as an RDS Dns pattern? 

We are looking into the wrapper to see how it works.

**Comment by sergiyvamz** [comment] 2023-04-04 18:45
Hello @arosso 

> That would make sense to me... if a new connection is created, and for whatever reason (e.g. DNS caching), it finds itself on a reader, it should be able to get the node metadata and reconnect to the writer instead.

The driver doesn't implement such logic. It strictly follows a connection string provided by a user app. Connection string is resolved through DNS and a the driver connects to a database node at that address. Opened connection is returned to a user app with no further checks. The driver doesn't perform any checks to identify whether connection is to a writer or to a reader node.

> I don't see a similar pattern like 5 when using the custom domain endpoint. It seems like the logic is slightly different. There still is debug about reading the topology but I never see the Connect statement. Maybe it's using a cached copy of the topology (but not printing it out) or runs through a different code path because it's not recognized as an RDS Dns pattern?

In some cases the driver may use cached topology and connect to a known writer (or a reader) rather than to a provided endpoint. Cluster endpoint is one of the cases.
https://github.com/awslabs/aws-mysql-jdbc/blob/2629c37e008e841e1d58ae682728e5a0d80ba269/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1017
https://github.com/awslabs/aws-mysql-jdbc/blob/2629c37e008e841e1d58ae682728e5a0d80ba269/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1075

**Comment by arosso** [comment] 2023-04-05 06:23
@sergiyvamz - A few more observations. 

* Isn't the line you pointed out:  https://github.com/awslabs/aws-mysql-jdbc/blob/2629c37e008e841e1d58ae682728e5a0d80ba269/src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java#L1075  not checking the case of a custom domain correctly then? I assume a custom domain + clusterInstanceHostPattern should be treated the same as a cluster writer endpoint? Maybe this is why the behavior is different.
* After some more investigation we've found that the DNS switchover is actually fairly 'unstable'. We are using machines that are on a private subnet on a VPC with the resolver provided by the VPC. Even with a TTL of 5, continually querying the DNS, we can see a time of sometimes 20-30 seconds in which the IP is unstable. It will go back and forth between the new IP and the old IP. I don't see how we can control this (we don't use anything on the Instance that caches) but it basically causes problems when a connection has to be re-connected using the endpoint in the jdbc url. There seem to be 3 cases where the connection could be closed with Hikari:
  1. While the connection is checked out and in use. Here as long as the Exception Override is defined properly, the failover happens and everything is ok. 
  2. While the connection is idle in the pool. Here, upon check out, Hikari seems to run the connection check and initiate the failover. The problem is that the Exception Override is not used here and it causes the connection to be closed. At that point if the DNS is unstable the connection might be made to the old node which is a reader. 
  3. When the connection has reached it's max life. In this case Hikari closes the connection and tries to open a new one. If this is done during DNS instability the connection might end up again on the wrong/old node. 
* It seems like the only way to deal with the situation is to have some SQL checks setup to check if the @innodb_read_only parameters is false. This still doesn't seem to solve all cases though. 
* It still seems like it should be possible for the implementation to pick the correct writer node given the topology information it has. If the connection ends up on a reader, could the driver not treat it as a failover and try to find the writer node using the metadata in the replica_host_status table?

**Comment by davecramer** [comment] 2024-06-24 12:31
Support for this driver will be ending July 25/2024 as per the https://github.com/awslabs/aws-mysql-jdbc/blob/main/CONTRIBUTING.md document. Any new features will be implemented in https://github.com/aws/aws-advanced-jdbc-wrapper

**Closed by davecramer** 2024-06-24 12:31 UTC
Labels: bug
