### ISSUE TITLE
IllegalArgumentException for ByteArrayOutputStream

### ISSUE THREAD

**Issue by fgoldenberg-sdl** [awslabs/aws-mysql-jdbc#347] opened 2023-01-23 08:38 UTC
### Describe the bug

Description already at https://github.com/awslabs/aws-mysql-jdbc/issues/274
Can it be reopened please?

### Expected Behavior

[See above](https://github.com/awslabs/aws-mysql-jdbc/issues/274)

### Current Behavior

https://github.com/awslabs/aws-mysql-jdbc/issues/274

### Reproduction Steps

https://github.com/awslabs/aws-mysql-jdbc/issues/274

### The AWS JDBC Driver for MySQL version used

1.1.3

### JDK version used

JDK 17

### Operating System and version

Windows 10 enterprise

**Comment by karenc-bq** [comment] 2023-01-23 21:09
Hi @fgoldenberg-sdl, thank your for raising this issue. We will take a look and keep you updated with our investigation. To help us root cause the issue, can you please answer the following question?
- The exception thrown comes directly from the community code, do you observe the same behaviour when using the community driver: https://github.com/mysql/mysql-connector-j?

**Comment by karenc-bq** [comment] 2023-01-25 00:29
Hi @fgoldenberg-sdl, we are able to reproduce the error and we can see that the error comes from the community code: https://github.com/mysql/mysql-connector-j/blob/fa4912a849140828e48162a2c396c8df0091bed7/src/main/protocol-impl/java/com/mysql/cj/protocol/a/AbstractValueEncoder.java#L227.
Unfortunately, since this is a bug from the community code, we are unable to resolve it at the moment. We will share these findings to determine a path forward. 

In the meantime, below are more details about the bug if you are interested.

--- 

When inserting a large binary array, the driver eventually ends up this line of code:
```java
ByteArrayOutputStream bOut = new ByteArrayOutputStream((x.length * 2) + 3);
```
Where x is the binary data to be ingested. Say the binary data to be ingested is 1.5Gb, this `(x.length * 2) + 3` integer multiplication results in an overflow and thus resulting the exception you have been seeing.

Below is the test code snippet I used to reproduce the error on both the AWS MySQL Driver and the community driver:
```java
try (Connection conn = DriverManager.getConnection(CONNECTION_URL, properties);
    Statement statement = conn.createStatement()) {

  statement.executeUpdate("CREATE TABLE `data` (`distid` binary(16) NOT NULL)");
  final PreparedStatement preparedStatement = conn.prepareStatement("INSERT INTO data VALUES(?)");

  final File file = new File("1.5GbFile.txt");
  byte[] bytes = new byte[(int) file.length()];
  try (FileInputStream input = new FileInputStream(file)) {
    input.read(bytes);
  }

  System.out.println("byte array size: " + bytes.length);
  preparedStatement.setBytes(1, bytes);

  preparedStatement.executeLargeUpdate();
}
```

**Comment by karenc-bq** [comment] 2023-01-25 20:30
Hi @fgoldenberg-sdl, thank you again for raising this issue. We will be closing this issue for now but we are still tracking community related bugs internally.

**Closed by karenc-bq** 2023-01-25 20:30 UTC
Labels: community bug
